// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';

import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';

const local = path.resolve(__dirname, '.env.local');
const envPath = fs.existsSync(local) ? local : path.resolve(__dirname, '.env');
dotenv.config({ path: envPath });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DIRECT_URL'],
  },
});
