// ═══════════════════════════════════════════════════════════════════════════
// iTECify Mock Data Types
// These types mirror the Prisma schema that will be created later.
// When integrating with the backend, these types will be generated by Prisma.
// ═══════════════════════════════════════════════════════════════════════════

export interface User {
  id: string
  name: string
  email: string
  avatarUrl: string | null
  /** HSL color assigned for presence (e.g. "hsl(239, 84%, 67%)") */
  cursorColor: string
}

export interface Project {
  id: string
  name: string
  description: string | null
  language: string
  createdAt: string
  updatedAt: string
  ownerId: string
  collaborators: User[]
}

export interface FileNode {
  /** Full path e.g. "/src/components/Button.tsx" — flat map key */
  path: string
  content: string
  language: string
}

export interface PresenceUser extends User {
  /** File path the user is currently viewing */
  activeFile: string | null
  /** Cursor position in the active file */
  cursorPosition: { line: number; column: number } | null
  isTyping: boolean
  isOnline: boolean
}

export interface AIAgent {
  id: string
  name: string
  persona: string
  avatarUrl: string | null
  systemPrompt: string
  color: string
  isActive: boolean
}

export interface AIZoneBlock {
  id: string
  agentId: string
  filePath: string
  startLine: number
  endLine: number
  originalCode: string
  suggestedCode: string
  prompt: string
  status: "generating" | "pending" | "accepted" | "rejected"
}

export interface TerminalLine {
  id: string
  type: "stdin" | "stdout" | "stderr"
  content: string
  timestamp: string
  userId?: string
}

export interface Snapshot {
  id: string
  projectId: string
  createdAt: string
  label: string | null
  /** Number of lines changed since previous snapshot */
  changeCount: number
  userId: string
}
